/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_de_Cadastro;

/**
 *
 * @author roger
 */
import javax.swing.JOptionPane;
public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_Nome = new javax.swing.JLabel();
        l_Sobrenome = new javax.swing.JLabel();
        l_Cpf = new javax.swing.JLabel();
        Txt_Nome = new javax.swing.JTextField();
        Txt_Sobrenome = new javax.swing.JTextField();
        Txt_Cpf = new javax.swing.JTextField();
        l_Genero = new javax.swing.JLabel();
        C_Genero = new javax.swing.JComboBox<>();
        l_Endereço = new javax.swing.JLabel();
        Txt_Endereço = new javax.swing.JTextField();
        b_Prosseguir = new javax.swing.JButton();
        C_Termos_Uso = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_Nome.setText("Nome:");
        getContentPane().add(l_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 37, -1));

        l_Sobrenome.setText("Sobrenome:");
        getContentPane().add(l_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        l_Cpf.setText("CPF:");
        getContentPane().add(l_Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(Txt_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, -1));
        getContentPane().add(Txt_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 160, -1));
        getContentPane().add(Txt_Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, -1));

        l_Genero.setText("Gênero:");
        getContentPane().add(l_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        C_Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", " " }));
        C_Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_GeneroActionPerformed(evt);
            }
        });
        getContentPane().add(C_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        l_Endereço.setText("Endereço:");
        getContentPane().add(l_Endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(Txt_Endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, -1));

        b_Prosseguir.setText("Prosseguir");
        b_Prosseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ProsseguirActionPerformed(evt);
            }
        });
        getContentPane().add(b_Prosseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 40));

        C_Termos_Uso.setText("Aceitar Termos de Uso");
        getContentPane().add(C_Termos_Uso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/img_fundo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_ProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ProsseguirActionPerformed
    new Informaçoes_adicionais().setVisible(true);
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_ProsseguirActionPerformed

    private void C_GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_GeneroActionPerformed
    

        // TODO add your handling code here:
    }//GEN-LAST:event_C_GeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> C_Genero;
    private javax.swing.JCheckBox C_Termos_Uso;
    private javax.swing.JTextField Txt_Cpf;
    private javax.swing.JTextField Txt_Endereço;
    private javax.swing.JTextField Txt_Nome;
    private javax.swing.JTextField Txt_Sobrenome;
    private javax.swing.JButton b_Prosseguir;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l_Cpf;
    private javax.swing.JLabel l_Endereço;
    private javax.swing.JLabel l_Genero;
    private javax.swing.JLabel l_Nome;
    private javax.swing.JLabel l_Sobrenome;
    // End of variables declaration//GEN-END:variables
}
