/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_de_Cadastro;

/**
 *
 * @author roger
 */
import javax.swing.JOptionPane;
public class Informaçoes_adicionais extends javax.swing.JFrame {

    /**
     * Creates new form Informaçoes_adicionais
     */
    public Informaçoes_adicionais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l_Estado = new javax.swing.JLabel();
        l_Cidade = new javax.swing.JLabel();
        l_Email = new javax.swing.JLabel();
        l_Telefone = new javax.swing.JLabel();
        l_Profissao = new javax.swing.JLabel();
        l_Cep = new javax.swing.JLabel();
        Txt_Cidade = new javax.swing.JTextField();
        Txt_Cep = new javax.swing.JTextField();
        Txt_Email = new javax.swing.JTextField();
        C_Estado = new javax.swing.JComboBox<>();
        Txt_Telefone = new javax.swing.JTextField();
        Txt_Profissao = new javax.swing.JTextField();
        l_Escolaridade = new javax.swing.JLabel();
        c_Ensino_Fundamental = new javax.swing.JRadioButton();
        c_Ensino_Medio = new javax.swing.JRadioButton();
        c_Ensino_Superior = new javax.swing.JRadioButton();
        l_Pais = new javax.swing.JLabel();
        C_Brasil = new javax.swing.JCheckBox();
        C_Portugal = new javax.swing.JCheckBox();
        C_Argentina = new javax.swing.JCheckBox();
        C_EUA = new javax.swing.JCheckBox();
        C_Outros = new javax.swing.JCheckBox();
        l_Estado_Civil = new javax.swing.JLabel();
        C_Solteiro = new javax.swing.JRadioButton();
        C_Casado = new javax.swing.JRadioButton();
        C_Viuvo = new javax.swing.JRadioButton();
        b_Alterar = new javax.swing.JButton();
        b_Cadastrar = new javax.swing.JButton();
        b_Excluir = new javax.swing.JButton();
        b_Sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/img_fundo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informaçoes Adicionais");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_Estado.setText("Estado:");
        getContentPane().add(l_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        l_Cidade.setText("Cidade:");
        getContentPane().add(l_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        l_Email.setText("Email:");
        getContentPane().add(l_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 37, -1));

        l_Telefone.setText("Telefone:");
        getContentPane().add(l_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        l_Profissao.setText("Profissao:");
        getContentPane().add(l_Profissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        l_Cep.setText("Cep:");
        getContentPane().add(l_Cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 37, -1));

        Txt_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CidadeActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 166, -1));
        getContentPane().add(Txt_Cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 169, -1));
        getContentPane().add(Txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 169, -1));

        C_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RJ", "SP", "ES", "MG", "OUTROS..." }));
        getContentPane().add(C_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        Txt_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 157, -1));
        getContentPane().add(Txt_Profissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 156, -1));

        l_Escolaridade.setText("Escolaridade:");
        getContentPane().add(l_Escolaridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        c_Ensino_Fundamental.setText("Ensino Fundamental completo");
        getContentPane().add(c_Ensino_Fundamental, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        c_Ensino_Medio.setText("Ensino Medio completo");
        getContentPane().add(c_Ensino_Medio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        c_Ensino_Superior.setText("Ensino Superior completo");
        getContentPane().add(c_Ensino_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        l_Pais.setText("País:");
        getContentPane().add(l_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        C_Brasil.setText("Brasil");
        getContentPane().add(C_Brasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 63, -1));

        C_Portugal.setText("Portugal");
        getContentPane().add(C_Portugal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 73, -1));

        C_Argentina.setText("Argentina");
        C_Argentina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ArgentinaActionPerformed(evt);
            }
        });
        getContentPane().add(C_Argentina, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 80, -1));

        C_EUA.setText("EUA");
        C_EUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_EUAActionPerformed(evt);
            }
        });
        getContentPane().add(C_EUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 54, -1));

        C_Outros.setText("Outros...");
        getContentPane().add(C_Outros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        l_Estado_Civil.setText("Estado Civil:");
        getContentPane().add(l_Estado_Civil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        C_Solteiro.setText("Solteiro(a)");
        getContentPane().add(C_Solteiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        C_Casado.setText("Casado(a)");
        getContentPane().add(C_Casado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        C_Viuvo.setText("Viuvo(a)");
        getContentPane().add(C_Viuvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        b_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/alterar.png"))); // NOI18N
        b_Alterar.setText("Alterar");
        b_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AlterarActionPerformed(evt);
            }
        });
        getContentPane().add(b_Alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 180, 40));

        b_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/cadastrar.png"))); // NOI18N
        b_Cadastrar.setText("Cadastrar");
        b_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(b_Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, 40));

        b_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/excluir.png"))); // NOI18N
        b_Excluir.setText("Excluir");
        b_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(b_Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 170, 40));

        b_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/1714352255239 (1) (2).png"))); // NOI18N
        b_Sair.setText("Sair");
        b_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SairActionPerformed(evt);
            }
        });
        getContentPane().add(b_Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 170, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_de_Cadastro/img_fundo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefoneActionPerformed

    private void C_ArgentinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ArgentinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_ArgentinaActionPerformed

    private void C_EUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_EUAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_EUAActionPerformed

    private void b_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CadastrarActionPerformed
    JOptionPane.showMessageDialog(null, "Usuario Cadastrado");
    System.exit(0);
    // TODO add your handling code here:
    }//GEN-LAST:event_b_CadastrarActionPerformed

    private void b_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_b_SairActionPerformed

    private void Txt_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CidadeActionPerformed

    private void b_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AlterarActionPerformed
    Txt_Cidade.setText("");
    Txt_Cep.setText("");
    Txt_Email.setText("");
    Txt_Telefone.setText("");
    Txt_Profissao.setText("");
    
    c_Ensino_Fundamental.setSelected(false);
    c_Ensino_Medio.setSelected(false);
    c_Ensino_Superior.setSelected(false);
   
    C_Solteiro.setSelected(false);
    C_Casado.setSelected(false);
    C_Viuvo.setSelected(false);
    
    C_Brasil.setSelected(false);
    C_Portugal.setSelected(false);
    C_Argentina.setSelected(false);
    C_EUA.setSelected(false);
    C_Outros.setSelected(false);
    
    C_Estado.setSelectedIndex(-1);
    JOptionPane.showMessageDialog(null, "cadastro alterado");
    }//GEN-LAST:event_b_AlterarActionPerformed

    private void b_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ExcluirActionPerformed
    getContentPane().remove(Txt_Cidade);
    getContentPane().remove(Txt_Cep);
    getContentPane().remove(Txt_Telefone);
    getContentPane().remove(Txt_Email);
    getContentPane().remove(Txt_Profissao);
    
    C_Estado.setSelectedIndex(-1);
    
    C_Solteiro.setSelected(false);
    C_Casado.setSelected(false);
    C_Viuvo.setSelected(false);
    
    C_Brasil.setSelected(false);
    C_Portugal.setSelected(false);
    C_Argentina.setSelected(false);
    C_EUA.setSelected(false);
    C_Outros.setSelected(false);
    
    c_Ensino_Fundamental.setSelected(false);
    c_Ensino_Medio.setSelected(false);
    c_Ensino_Superior.setSelected(false);
    getContentPane().revalidate();
    getContentPane().repaint();
    JOptionPane.showMessageDialog(null, "cadastro excluido");
    System.exit(0);
    }//GEN-LAST:event_b_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informaçoes_adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informaçoes_adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informaçoes_adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informaçoes_adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informaçoes_adicionais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox C_Argentina;
    private javax.swing.JCheckBox C_Brasil;
    private javax.swing.JRadioButton C_Casado;
    private javax.swing.JCheckBox C_EUA;
    private javax.swing.JComboBox<String> C_Estado;
    private javax.swing.JCheckBox C_Outros;
    private javax.swing.JCheckBox C_Portugal;
    private javax.swing.JRadioButton C_Solteiro;
    private javax.swing.JRadioButton C_Viuvo;
    private javax.swing.JTextField Txt_Cep;
    private javax.swing.JTextField Txt_Cidade;
    private javax.swing.JTextField Txt_Email;
    private javax.swing.JTextField Txt_Profissao;
    private javax.swing.JTextField Txt_Telefone;
    private javax.swing.JButton b_Alterar;
    private javax.swing.JButton b_Cadastrar;
    private javax.swing.JButton b_Excluir;
    private javax.swing.JButton b_Sair;
    private javax.swing.JRadioButton c_Ensino_Fundamental;
    private javax.swing.JRadioButton c_Ensino_Medio;
    private javax.swing.JRadioButton c_Ensino_Superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l_Cep;
    private javax.swing.JLabel l_Cidade;
    private javax.swing.JLabel l_Email;
    private javax.swing.JLabel l_Escolaridade;
    private javax.swing.JLabel l_Estado;
    private javax.swing.JLabel l_Estado_Civil;
    private javax.swing.JLabel l_Pais;
    private javax.swing.JLabel l_Profissao;
    private javax.swing.JLabel l_Telefone;
    // End of variables declaration//GEN-END:variables
}
